<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLPE3911\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLPE3911/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLPE3911.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLPE3911\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLPE3911\App_KernelDevDebugContainer([
    'container.build_hash' => 'LPE3911',
    'container.build_id' => '93b4538e',
    'container.build_time' => 1727265829,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLPE3911');
